### ISSUE TITLE
f-component 'invisible' status not working

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/transforms#46]
The status="invisible" attribute for an f-component is not currently working to hide the SFR. See for example the un-iterated FIA_PSK_EXT.1 in authserver (which is intended to be invisible so that it only exists in the ECD).

**Comment by kgal** [comment]
I cannot see where FIA_PSK_EXT.1 (mistakenly) exists in the body. You can link to https://commoncriteria.github.io/pp/authserver/authserver-release-linkable.html (all periods are anchors).

**Comment by jfisherbah** [comment]
Here it is: https://commoncriteria.github.io/pp/authserver/authserver-release-linkable.html#period_517 

The un-iterated FIA_PSK_EXT.1 that is linked here is supposed to be invisible and only exists for the purpose of the ECD. The iteration FIA_PSK_EXT.1/AuthSvr right below it is the only one that's actually supposed to be present in that section.

**Comment by kgal** [comment]
I updated the transforms and that seemed to fix it:
https://commoncriteria.github.io/pp/authserver/authserver-release.html#FIA_PSK_EXT.1.1/AuthSvr

The linkable version still seems to have those in there, which I'm having trouble figuring out, but the plain release seems okay.

**Comment by jfisherbah** [comment]
I see it's resolved in the release version as well, but it's also present in the combined module-SD version 'authserver.html' in addition to the linkable one.

**Comment by kgal** [comment]
The SD should be working now.

**Comment by jfisherbah** [comment]
issue is still present in the combined module-EAs (authserver.html) and in the linkable one

**Comment by jfisherbah** [comment]
@robertmclemons bumping this as it is still an open issue with the latest transforms. Specifically, the un-iterated FTP_BLT_EXT.3 in the Bluetooth module is flagged as invisible because it only exists for the purpose of the ECD but it is still visible in section 5.3 of https://commoncriteria.github.io/bluetooth/master/bluetooth.html. 

![Image](https://github.com/user-attachments/assets/5a716979-6620-406e-9a82-0a01ef41dfd5)

Note that it is correctly invisible in bluetooth-release.html but that is the version without EAs so that will not be the one that is used moving forward.

**Comment by jfisherbah** [comment]
confirmed fixed
